version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: lumine-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=lumine_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - lumine-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongodb:
    image: mongo:7.0
    container_name: lumine-mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db
    networks:
      - lumine-net

  redis:
    image: redis:alpine
    container_name: lumine-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - lumine-net
    command: redis-server --appendonly yes

  zipkin:
    image: openzipkin/zipkin
    container_name: lumine-zipkin
    ports:
      - "9411:9411"
    networks:
      - lumine-net

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: lumine-keycloak
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
     - "8181:8080"
    networks:
     - lumine-net

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: lumine-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - lumine-net

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: lumine-kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - lumine-net

volumes:
  postgres-data:
  mongo-data:
  redis-data:

networks:
  lumine-net:
    driver: bridge