apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:24.0.1
          args: ["start-dev"] # developer mode (No HTTPS required)
          ports:
            - containerPort: 8080
          env:
            - name: KEYCLOAK_ADMIN
              value: "admin"
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: "admin"
            # ️IMPORTANT: Allow access from outside the cluster
            - name: KC_PROXY
              value: "edge"

            - name: KC_DB
              value: postgres
            - name: KC_DB_URL
              value: jdbc:postgresql://postgres:5432/keycloak
            - name: KC_DB_USERNAME
              value: admin
            - name: KC_DB_PASSWORD
              value: password
            - name: KC_HOSTNAME_STRICT
              value: "false" # Helps prevent redirect loops in dev

---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
spec:
  selector:
    app: keycloak
  type: LoadBalancer # Exposes it to your browser
  ports:
    - protocol: TCP
      port: 8181       # You visit this port
      targetPort: 8080 # Container listens on this port