apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: lumine/order-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8083
          env:
            # database connection
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/lumine_db
            - name: SPRING_DATASOURCE_USERNAME
              value: admin
            - name: SPRING_DATASOURCE_PASSWORD
              value: password
            # kafka Connection
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
            # discovery and tracing
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://discovery-service:8761/eureka/
            - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
              value: http://zipkin:9411/api/v2/spans
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "true"
            - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
              value: "prometheus,health,info,metrics"

---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order-service
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083