apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: lumine/product-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
              #mongo
            - name: SPRING_DATA_MONGODB_URI
              value: mongodb://mongodb:27017/product-service
              #eureka
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://discovery-service:8761/eureka/
            - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
              value: http://zipkin:9411/api/v2/spans

            # 500, magic fix for spring cloud kubernetes
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "true"

---
apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  selector:
    app: product-service
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081